const members=[
    {
        id:1,
        name:"L. Messi",
        age:31,
        nationality:"Argentina",
        overall:94,
        club:"FC Barcelona",
        value:"110.5 M",
        wage:"565 K",
        preferredFoot:"Left",
        workRate:"Medium/Medium",
        position:"RF",
        jerseyNo:10,
        Joined:"1 JULY 2004",
        validity:2021,
        height:"5'7",
        weight:"159 lbs",
        crossing:84,
        finishing:95,
        headingAccuracy:70,
        shortPassing:90,
        volleys:86,
        img:"../Assets/messi.jpg"
    },
    {
        id:2,
        name:"Cristiano Ronaldo",
        age:33,
        nationality:"Portugal",
        overall:94,
        club:"Juventus",
        value:"77 M",
        wage:"405 K",
        preferredFoot:"Right",
        workRate:"High/Low",
        position:"ST",
        jerseyNo:7,
        Joined:"10 JULY 2018",
        validity:2022,
        height:"6'2",
        weight:"183 lbs",
        crossing:84,
        finishing:94,
        headingAccuracy:89,
        shortPassing:81,
        volleys:87,
        img:"../Assets/ronaldo.png"
    },
    {
        id:3,
        name:"Neymar Jr",
        age:26,
        nationality:"Brazil",
        overall:92,
        club:"Paris Saint-Germain",
        value:"118.5 M",
        wage:"290 K",
        preferredFoot:"Right",
        workRate:"High/Medium",
        position:"LW",
        jerseyNo:10,
        Joined:"3 AUG 2017",
        validity:2022,
        height:"5'9",
        weight:"150 lbs",
        crossing:79,
        finishing:87,
        headingAccuracy:62,
        shortPassing:84,
        volleys:84,
        img:"../Assets/neymar.jpg"
    },
    {
        id:4,
        name:"De Gea",
        age:27,
        nationality:"Spain",
        overall:91,
        club:"Manchester United",
        value:"72 M",
        wage:"260 K",
        preferredFoot:"Right",
        workRate:"Medium/Medium",
        position:"GK",
        jerseyNo:1,
        Joined:"1 JULY 2011",
        validity:2020,
        height:"6'4",
        weight:"168 lbs",
        crossing:17,
        finishing:13,
        headingAccuracy:21,
        shortPassing:50,
        volleys:13,
        img:"../Assets/gea.jpg"
    },
    {
        id:5,
        name:"K. De Bruyne",
        age:27,
        nationality:"Belgium",
        overall:91,
        club:"Manchester City",
        value:"102 M",
        wage:"355 K",
        preferredFoot:"Right",
        workRate:"High/High",
        position:"RCM",
        jerseyNo:7,
        Joined:"30 AUG 2015",
        validity:2023,
        height:"5'11",
        weight:"154 lbs",
        crossing:93,
        finishing:82,
        headingAccuracy:55,
        shortPassing:92,
        volleys:82,
        img:"../Assets/bruyne.png"
    }
];

export default members;